on:
  workflow_dispatch:
  issues:
    types:
      - created
      - opened
jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo running job1
  job2:
    name: Cowsays
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - name: Ship it
      uses: mscoutermarsh/cowsays-action@master
      with:
        text: 'ship ship ship!'
        color: 'red'
